"""empty message

Revision ID: 413ca9be5354
Revises: 9b9b5cfe1201
Create Date: 2023-10-17 12:24:11.197707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413ca9be5354'
down_revision = '9b9b5cfe1201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('payment_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payment_ibfk_1', 'user', ['student_id'], ['user_id'])

    # ### end Alembic commands ###
