"""empty message

Revision ID: 4cf6650e694f
Revises: 5066925be424
Create Date: 2023-10-22 12:23:19.788188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cf6650e694f'
down_revision = '5066925be424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailyreport',
    sa.Column('daily_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('daily_report', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('daily_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dailyreport')
    # ### end Alembic commands ###
