"""empty message

Revision ID: 4d10aac84b62
Revises: b352adb40cc4
Create Date: 2023-10-14 07:42:19.598308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d10aac84b62'
down_revision = 'b352adb40cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_column('comments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
