"""empty message

Revision ID: 84564f939019
Revises: 74c33df778a1
Create Date: 2023-10-14 06:37:26.957676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84564f939019'
down_revision = '74c33df778a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_column('comments')

    # ### end Alembic commands ###
