"""empty message

Revision ID: 9b9b5cfe1201
Revises: e5ed39ef8536
Create Date: 2023-10-17 12:04:19.191453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b9b5cfe1201'
down_revision = 'e5ed39ef8536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acc_session', sa.String(length=100), nullable=False))
        batch_op.drop_column('session')

    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_constraint('result_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.create_foreign_key('result_ibfk_2', 'students', ['student_id'], ['student_id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('acc_session')

    # ### end Alembic commands ###
