"""empty message

Revision ID: e5ed39ef8536
Revises: 4d10aac84b62
Create Date: 2023-10-17 11:45:58.114077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ed39ef8536'
down_revision = '4d10aac84b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.Enum('Successful', 'Fail', 'Pending'), nullable=True))
        batch_op.add_column(sa.Column('ref_no', sa.Float(), nullable=False))

    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_constraint('result_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('result_ibfk_1', 'students', ['student_id'], ['student_id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('ref_no')
        batch_op.drop_column('payment_status')

    # ### end Alembic commands ###
